Game logic
Elijahscriptdev/oppruby pull request #1
Opened 2019-12-02 20:11 UTC by Elijahscriptdev

Milestone 3

2019-12-03 22:52 UTC, maelfosso requested changes
# Changes required

Hello @Elijahscriptdev 

0. Could you please, display the empty board before asking the player to play is first move ?

1. We should be able to run the game with only `bin/main.rb`. I got an error when trying

2. Except for **draw** state, the game doesn't any of winning state, weither is the horizontal, vertical or diagonal one.

3. Read the comments below.

4. Fix the sticklers errors.

Kindly make the changes and submit a new code review request
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-12-03 22:52 UTC, maelfosso commented on lib/player.rb
> +  end
no `puts` nor `gets` nor `print` in any logic files

2019-12-03 22:52 UTC, maelfosso commented on lib/player.rb
> +  attr_accessor :choice, :player, :count
`attr_accessor` is not allowed

2019-12-03 22:52 UTC, maelfosso commented on lib/board.rb
> +  attr_accessor :game_board, :board_num
`attr_accessor` is not allowed.
Choose between `attr_reader` or `attr_writer`

2019-12-03 22:52 UTC, maelfosso commented on lib/board.rb
> +  end
Where is WIN ?
Could define it here ?

2019-12-03 22:52 UTC, maelfosso commented on lib/tic_tac_toe.rb
> +end
No puts in logic files

2019-12-03 22:52 UTC, maelfosso commented on lib/player.rb
> +  end
I suggest you to move that method into the Board class. 
There is no reason to keep it in the Player class:
- It doesn't use anything from that class
- The Player class could work without this method

On the other hand, the simple fact that you pass the board, `@board.game_board` from the Board class, as a parameter in that method means that you can have the same method into the Board class  and 
```ruby
def num_choice(choice)
    ...
    until @game_board[choice - 1] == ' ' && choice.between?(1, 9)
      puts 'Wrong choice!!!!!!!!!!!'
      puts 'Please input another number between 1-9 and not used already'
      ...
    end
    ...
  end
```
That is just a mock as an example

2019-12-03 22:52 UTC, maelfosso commented on lib/board.rb
> +  end
This method is not working!!!

2019-12-05 17:21 UTC, uche-inyama approved these changes
## Approved

Hi Elijah!

Everything is working fine, go ahead and merge into development.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama```

2019-12-05 17:34 UTC, merged